### ISSUE TITLE
这是什么情况呢，zbar软件也安装好了,linux下能使用。但是代码还是报错，求指教~~

### ISSUE THREAD

**Issue by zouhuigang** [happyEgg/go_qrcode#1]
github.com/happyEgg/go_qrcode : fatal error: zbar.h: No such file or directory
 // #include <zbar.h>
                   ^
compilation terminated.

**Comment by happyEgg** [comment]
@zouhuigang 你没有这个zbar.h这个库，你百度一下安装就可以了

**Comment by zouhuigang** [comment]
恩恩，太谢谢了，已经安装好啦~~~
